// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fichaTecnica.Data;

namespace fichaTecnica.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200928230526_RefatorandoItemInsumo")]
    partial class RefatorandoItemInsumo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("fichaTecnica.Models.FichaTecnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("DescricaoDaFichaTecnica")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("RendimentoDaPorcao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FichaTecnicas");
                });

            modelBuilder.Entity("fichaTecnica.Models.FichaTecnicaInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FichaTecnicaId")
                        .HasColumnType("int");

                    b.Property<int>("ItemInsumoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FichaTecnicaId");

                    b.HasIndex("ItemInsumoId");

                    b.ToTable("FichaTecnicaInsumos");
                });

            modelBuilder.Entity("fichaTecnica.Models.ItemInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CustoTotal")
                        .HasColumnType("float");

                    b.Property<double>("CustoUnitario")
                        .HasColumnType("float");

                    b.Property<string>("DescricaoItemInsumo")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TipoDeUnidadeDeMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemInsumos");
                });

            modelBuilder.Entity("fichaTecnica.Models.FichaTecnicaInsumo", b =>
                {
                    b.HasOne("fichaTecnica.Models.FichaTecnica", "FichaTecnica")
                        .WithMany()
                        .HasForeignKey("FichaTecnicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fichaTecnica.Models.ItemInsumo", "ItemInsumo")
                        .WithMany()
                        .HasForeignKey("ItemInsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
